# Generated by Django 5.1.4 on 2026-05-17 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10, null=True)),
                ('hours_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('current_approval_level', models.IntegerField(default=1)),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='employees.employee')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField()),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.leaveapplication')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to='employees.employee')),
            ],
            options={
                'ordering': ['level', 'actioned_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('accrual_type', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('annual', 'Annual (Jan 1)'), ('on_join', 'On joining date'), ('manual', 'Manual')], default='on_join', max_length=20)),
                ('accrual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_balance', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('carryover_limit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('encashable', models.BooleanField(default=False)),
                ('gender_restriction', models.CharField(choices=[('none', 'All genders'), ('male', 'Male only'), ('female', 'Female only')], default='none', max_length=10)),
                ('min_notice_days', models.IntegerField(default=0)),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('allow_half_day', models.BooleanField(default=False)),
                ('allow_hourly', models.BooleanField(default=False)),
                ('allow_backdate', models.BooleanField(default=False)),
                ('approval_levels', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to', models.CharField(default='all', max_length=20)),
                ('color', models.CharField(default='#10b981', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='leaves.leavetype'),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='leaves.holidaycalendar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carried_over', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['employee', 'status'], name='leaves_leav_employe_aa6ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leaves_leav_start_d_352125_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('calendar', 'date')},
        ),
    ]
