# Generated by Django 5.1.4 on 2026-05-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='address_during_leave',
            field=models.TextField(blank=True, default='', help_text='Employee address during leave'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='contact_during_leave',
            field=models.CharField(blank=True, default='', help_text='Employee phone number during leave', max_length=20),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='duty_date_for_cd',
            field=models.DateField(blank=True, help_text='Date of duty on second rest (CD leave only)', null=True),
        ),
    ]
