# Generated by Django 5.1.4 on 2026-05-21 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_experience_start_date'),
        ('leaves', '0002_leaveapplication_address_during_leave_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='splits_allowed',
            field=models.IntegerField(default=0, help_text='Max splits allowed for this employee/type/year'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='splits_used',
            field=models.IntegerField(default=0, help_text='Number of leave splits taken this year'),
        ),
        migrations.CreateModel(
            name='LeaveQuotaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('old_allocated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new_allocated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('old_splits_allowed', models.IntegerField(default=0)),
                ('new_splits_allowed', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=200)),
                ('triggered_by', models.CharField(default='system', help_text='system / hr_manual / year_end / monthly_job', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_logs', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_logs', to='leaves.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
