# Generated by Django 5.1.4 on 2026-06-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_experience_start_date'),
        ('leaves', '0004_add_expired_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='shift_incharge',
            field=models.ForeignKey(blank=True, help_text='Shift Incharge selected by employee at apply time for Level-2 approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sic_leaves', to='employees.employee'),
        ),
    ]
