# Generated by Django 5.1.4 on 2026-05-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_code',
            field=models.CharField(blank=True, default='', help_text='Payroll / ERP account code (Employee A/C Code)', max_length=50),
        ),
    ]
