# Generated by Django 5.1.4 on 2026-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience_start_date',
            field=models.DateField(blank=True, help_text='Career start date (may predate joining this company). Used to calculate total experience for leave quota.', null=True),
        ),
    ]
