# Generated by Django 5.1.4 on 2026-06-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_experience_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_incharge_for', to='employees.employee'),
        ),
    ]
