# Generated by Django 5.1.4 on 2026-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_shift_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='p_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
